name: Flutter CI

on:
  pull_request:

concurrency:
  group: pr-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: "pubspec.yaml"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build web
        run: flutter build web

      - name: Build android apk
        run: flutter build apk

  build-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: "pubspec.yaml"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build ios
        run: flutter build ios --no-codesign
