name: Deploy docs to release branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Checkout release branch
        run: |
          git fetch origin release:release || git checkout --orphan release
          git checkout release

      - name: Set git committer
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Merge main into release
        run: git merge --no-ff origin/main

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: "pubspec.yaml"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Update base href in index.html
        run: sed -i '' 's|<base href=\"/\">|<base href=\"/yumemi-flutter-engineer-codecheck/\">|' build/web/index.html

      - name: Remove old docs
        run: rm -rf docs

      - name: Move build to docs
        run: mv build/web ../docs

      - name: Commit and push to release
        run: |
          git add docs
          git commit -m "chore: update docs with latest web build [skip ci]" || echo "No changes to commit"
          git push origin release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
